---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install dependencies for testing
      package:
        name: "hostname"
        state: "present"
      become: true
  roles:
    - role: while_true_do.sys_hostname
